import type { ChapterDefinition } from '@/types/chronicle.types';

export const CHAPTERS: ChapterDefinition[] = [
  {
    id: 'birth',
    number: 1,
    title: 'The Beginning',
    subtitle: 'Birth & Origin Story',
    description: 'Every legend starts somewhere. Time to roll your origin stats.',
    questions: [
      {
        id: 'birth-name',
        prompt: 'Hero, what name was bestowed upon you at the start of your quest?',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'Name given',
        placeholder: 'The name on your character sheet...',
      },
      {
        id: 'birth-date',
        prompt: 'When did you first load into this server? (Your spawn date)',
        type: 'date',
        required: true,
        xp: 10,
        timelineLabel: 'Spawn date',
        placeholder: 'dd/mm/yyyy',
      },
      {
        id: 'birth-location',
        prompt: 'What was the name of your starting zone? (City/town of birth)',
        type: 'text',
        required: true,
        xp: 15,
        timelineLabel: 'Starting zone',
        placeholder: 'The hospital, suburb, or town where your quest began...',
      },
      {
        id: 'birth-weight',
        prompt: 'What were your base stats at character creation? (Birth weight, if known)',
        type: 'text',
        required: false,
        xp: 10,
        timelineLabel: 'Base stats',
        placeholder: 'e.g. 3.5 kg — your starting loadout weight',
      },
      {
        id: 'birth-parents',
        prompt: 'Who were the NPCs responsible for your character creation?',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'Origin NPCs',
        placeholder: 'Names, occupations, or anything you know about the people who brought you into the world...',
      },
      {
        id: 'birth-story',
        prompt: 'Any legendary tales from your arrival? (Dramatic birth story, family lore, etc.)',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Arrival lore',
        placeholder: 'Were you early, late, born in a taxi? Any family legends about the day you showed up...',
      },
      {
        id: 'birth-siblings',
        prompt: 'Were there other party members already in your starting guild? (Older siblings)',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Starting party',
        placeholder: 'Brothers, sisters, or anyone else already in the household when you arrived...',
      },
    ],
  },
  {
    id: 'early-years',
    number: 2,
    title: 'Tutorial Zone',
    subtitle: 'Ages 0–5, Earliest Memories',
    description: 'The tutorial levels — learning to walk, talk, and not eat things off the floor.',
    questions: [
      {
        id: 'early-first-memory',
        prompt: 'What is the earliest save file you can access? (First memory)',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'First memory',
        placeholder: 'A texture, a sound, the feel of carpet or grass — whatever fragment comes back first...',
      },
      {
        id: 'early-home',
        prompt: 'Describe your first home base. What did it feel like?',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'First home base',
        placeholder: 'The creak of floorboards, the smell of the kitchen, the temperature of the tiles underfoot...',
      },
      {
        id: 'early-favourite-toy',
        prompt: 'What was your first legendary item? (Favourite toy or comfort object)',
        type: 'text',
        required: false,
        xp: 15,
        timelineLabel: 'First legendary item',
        placeholder: 'A stuffed animal worn smooth, a blanket with a specific texture, a plastic dinosaur...',
      },
      {
        id: 'early-pet',
        prompt: 'Did your party have a companion creature? (Family pet)',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Companion creature',
        placeholder: 'Name, species, temperament — the warm weight of a dog on your lap or a cat weaving between your legs...',
      },
      {
        id: 'early-food',
        prompt: 'What consumable item restored your HP best? (Favourite childhood food)',
        type: 'text',
        required: false,
        xp: 10,
        timelineLabel: 'Favourite consumable',
        placeholder: 'The taste you can still recall — Vegemite toast, fairy bread, a specific biscuit...',
      },
      {
        id: 'early-fear',
        prompt: 'What was the first boss encounter that scared you? (Childhood fear)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'First boss fear',
        placeholder: 'The dark, a specific sound, thunderstorms rattling the windows in a Queensland wet season...',
      },
      {
        id: 'early-personality',
        prompt: 'According to guild elders, what character traits did you display early on?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Early traits',
        placeholder: 'Were you quiet or loud, cautious or reckless? What do family members say you were like...',
      },
    ],
  },
  {
    id: 'primary-school',
    number: 3,
    title: 'The Academy',
    subtitle: 'Primary School Years',
    description: 'You entered the Academy — a place of learning, lunch orders, and playground politics.',
    questions: [
      {
        id: 'primary-school-name',
        prompt: 'What Academy did you attend? (Primary school name)',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'Academy name',
        placeholder: 'The school name — bonus points if you remember the motto...',
      },
      {
        id: 'primary-best-friend',
        prompt: 'Who was your first real party member? (Best friend)',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'First party member',
        placeholder: 'Their name, what you did together, where you hung out at lunch...',
      },
      {
        id: 'primary-favourite-subject',
        prompt: 'Which skill tree did you invest in most? (Favourite subject)',
        type: 'text',
        required: true,
        xp: 15,
        timelineLabel: 'Main skill tree',
        placeholder: 'Maths, reading, art, sport — the one that made the school bell ring too soon...',
      },
      {
        id: 'primary-teacher',
        prompt: 'Which NPC mentor left the biggest mark? (Memorable teacher)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Key mentor NPC',
        placeholder: 'Their name, their classroom, the chalk dust or marker smell — what made them stand out...',
      },
      {
        id: 'primary-achievement',
        prompt: 'What was your proudest achievement unlocked at the Academy?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Academy achievement',
        placeholder: 'A race you won, a play you were in, a project you nailed, a merit certificate on the fridge...',
      },
      {
        id: 'primary-lunch',
        prompt: 'What was the go-to ration pack? (Typical school lunch)',
        type: 'text',
        required: false,
        xp: 10,
        timelineLabel: 'Ration pack',
        placeholder: 'Vegemite sandwiches, a Mamee noodle packet, a frozen popper that thawed by recess...',
      },
      {
        id: 'primary-trouble',
        prompt: 'Did you ever trigger a reputation penalty? (Getting in trouble)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Reputation penalty',
        placeholder: 'The sinking stomach of being sent to the principal, a note home, a playground incident...',
      },
      {
        id: 'primary-hobby',
        prompt: 'What side quest consumed your free time outside the Academy?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'After-school side quest',
        placeholder: 'Sport, collecting cards, riding bikes until the streetlights came on, building cubby houses...',
      },
    ],
  },
  {
    id: 'teens',
    number: 4,
    title: 'Coming of Age',
    subtitle: 'Teenage Years',
    description: 'The skill tree expanded, the stakes got higher, and the main quest got complicated.',
    questions: [
      {
        id: 'teens-high-school',
        prompt: 'Which advanced Academy did you transfer to? (High school)',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'Advanced Academy',
        placeholder: 'The high school name — the feel of a new uniform, bigger hallways, new faces...',
      },
      {
        id: 'teens-identity',
        prompt: 'What character class were you starting to become? (How did you see yourself?)',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Emerging class',
        placeholder: 'The sporty one, the quiet thinker, the funny one, the rebel — how did the world categorise you...',
      },
      {
        id: 'teens-music',
        prompt: 'What was the soundtrack to this chapter? (Music that defined your teens)',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Chapter soundtrack',
        placeholder: 'Bands, albums, the tinny sound of a portable speaker or headphones on the bus...',
      },
      {
        id: 'teens-friendship',
        prompt: 'Who were the core members of your party during this arc?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Core party',
        placeholder: 'The crew you sat with, snuck out with, or spent every weekend with...',
      },
      {
        id: 'teens-crush',
        prompt: 'Any companion quest storylines worth documenting? (First crush or relationship)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Companion quest',
        placeholder: 'The nervous energy, sweaty palms, passing notes — or choosing to skip this side quest entirely...',
      },
      {
        id: 'teens-hardest-moment',
        prompt: 'What was the toughest boss fight of your teenage arc?',
        type: 'textarea',
        required: true,
        xp: 35,
        timelineLabel: 'Toughest boss fight',
        placeholder: 'A loss, a failure, a family change, bullying — the thing that tested your resilience...',
      },
      {
        id: 'teens-discovery',
        prompt: 'What hidden talent or passion did you unlock during this chapter?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Talent unlocked',
        placeholder: 'Something you discovered you were good at or loved — a skill that stuck with you...',
      },
      {
        id: 'teens-leaving',
        prompt: 'How did it feel when this chapter ended? (Finishing school, turning 18)',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Chapter close',
        placeholder: 'Relief, sadness, excitement — the weight of a school bag for the last time...',
      },
    ],
  },
  {
    id: 'young-adult',
    number: 5,
    title: 'Open World',
    subtitle: '18–24, First Jobs, Independence',
    description: 'The training wheels came off. Welcome to the open world — no quest markers, no hand-holding.',
    questions: [
      {
        id: 'young-first-job',
        prompt: 'What was your first paid quest? (First job)',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'First paid quest',
        placeholder: 'The job title, the place, the smell of the break room, the feel of your first pay...',
      },
      {
        id: 'young-living',
        prompt: 'Where did you set up your first independent base camp?',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'First base camp',
        placeholder: 'A share house, a tiny flat, still at home — the creak of your own front door or lack thereof...',
      },
      {
        id: 'young-study',
        prompt: 'Did you pursue any advanced skill training? (Uni, TAFE, apprenticeship)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Advanced training',
        placeholder: 'What you studied, where, whether you finished — or chose a different path entirely...',
      },
      {
        id: 'young-mistake',
        prompt: 'What was your most educational wipe? (A mistake you learnt from)',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Educational wipe',
        placeholder: 'The cringe-worthy decision that turned into a life lesson — hindsight XP is real...',
      },
      {
        id: 'young-adventure',
        prompt: 'Did you embark on any exploration quests? (Travel, moving cities)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Exploration quest',
        placeholder: 'A trip, a sea change, the humidity of Brisbane vs somewhere completely different...',
      },
      {
        id: 'young-relationship',
        prompt: 'Any significant companion questlines during this chapter?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Companion questline',
        placeholder: 'A serious relationship, a heartbreak, learning what you actually want in a party member...',
      },
      {
        id: 'young-defining',
        prompt: 'What single event from this chapter shaped your character build the most?',
        type: 'textarea',
        required: true,
        xp: 35,
        timelineLabel: 'Defining event',
        placeholder: 'The moment that shifted your trajectory — a door that opened or closed...',
      },
    ],
  },
  {
    id: 'late-twenties',
    number: 6,
    title: 'The Grind',
    subtitle: '25–29, Career Building',
    description: 'The grind phase — levelling up your career, finances, and figuring out what actually matters.',
    questions: [
      {
        id: 'twenties-career',
        prompt: 'What profession did you spec into? (Career path at this stage)',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Career spec',
        placeholder: 'Your job title, industry, the daily rhythm — keyboard clicks, tools in hand, meetings...',
      },
      {
        id: 'twenties-ambition',
        prompt: 'What was the main quest objective you were grinding towards?',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Main objective',
        placeholder: 'A promotion, a business, financial freedom, a creative goal — the thing driving your daily grind...',
      },
      {
        id: 'twenties-home',
        prompt: 'Where was your base of operations? (Living situation)',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Base of operations',
        placeholder: 'Renting, bought a place, still moving around — the neighbourhood, the commute...',
      },
      {
        id: 'twenties-friendship-shift',
        prompt: 'How did your party composition change during The Grind?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Party changes',
        placeholder: 'Old mates drifting, new colleagues becoming friends, weddings and moves reshuffling everything...',
      },
      {
        id: 'twenties-health',
        prompt: 'How were you managing your HP and stamina? (Health and fitness)',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'HP management',
        placeholder: 'Gym routine, running, complete neglect — the physical reality of your late twenties...',
      },
      {
        id: 'twenties-lesson',
        prompt: 'What was the hardest-earned skill point from this chapter?',
        type: 'textarea',
        required: true,
        xp: 35,
        timelineLabel: 'Hard-earned lesson',
        placeholder: 'A lesson about work, money, people, or yourself that only came through grinding...',
      },
      {
        id: 'twenties-regret',
        prompt: 'Any side quests you wish you had accepted — or declined?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Missed side quest',
        placeholder: 'An opportunity not taken, a risk avoided, or something you wish you had said no to...',
      },
    ],
  },
  {
    id: 'thirties',
    number: 7,
    title: 'Peak Power',
    subtitle: '30–39, Major Life Decisions',
    description: 'Peak Power — you have the skills, the resources, and the big decisions to make.',
    questions: [
      {
        id: 'thirties-achievement',
        prompt: 'What was the biggest achievement unlocked in this decade?',
        type: 'textarea',
        required: true,
        xp: 35,
        timelineLabel: 'Biggest achievement',
        placeholder: 'A career milestone, a family milestone, something you built — the tangible result of years of effort...',
      },
      {
        id: 'thirties-family',
        prompt: 'Did your guild expand? (Marriage, kids, chosen family)',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Guild expansion',
        placeholder: 'A partner, children, a deepening of bonds — or a deliberate choice to keep the party small...',
      },
      {
        id: 'thirties-career-evolution',
        prompt: 'How did your character build evolve from your twenties spec?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Build evolution',
        placeholder: 'Same career but senior, a complete respec, or a side hustle that became the main quest...',
      },
      {
        id: 'thirties-loss',
        prompt: 'Did you face any significant loss or defeat in this chapter?',
        type: 'textarea',
        required: false,
        xp: 35,
        timelineLabel: 'Significant loss',
        placeholder: 'A death, a divorce, a failure — the heavy stuff that changed how you see the world...',
      },
      {
        id: 'thirties-home',
        prompt: 'Where was your stronghold during Peak Power? (Home and location)',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Stronghold',
        placeholder: 'The suburb, the house, the neighbourhood sounds — cicadas in summer, bin night on Wednesday...',
      },
      {
        id: 'thirties-values',
        prompt: 'What alignment shift happened in your thirties? (Changed beliefs or priorities)',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Alignment shift',
        placeholder: 'Something you used to believe that you no longer do, or a new priority that reshaped your decisions...',
      },
      {
        id: 'thirties-joy',
        prompt: 'What brought you the most joy during this chapter?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Greatest joy',
        placeholder: 'A moment, a routine, a person — the thing that recharged your stamina bar...',
      },
    ],
  },
  {
    id: 'forties',
    number: 8,
    title: 'The Plateau',
    subtitle: '40–49, Stability and Reflection',
    description: 'The Plateau — the view from up here is different. Time to take stock of the inventory.',
    questions: [
      {
        id: 'forties-reflection',
        prompt: 'Standing on The Plateau, how does the quest log look so far?',
        type: 'textarea',
        required: true,
        xp: 35,
        timelineLabel: 'Quest log review',
        placeholder: 'Looking back at all the chapters — what pattern do you see in your story so far...',
      },
      {
        id: 'forties-career-status',
        prompt: 'What is your current profession and rank? (Career at this stage)',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'Current rank',
        placeholder: 'Your title, your daily work, whether it still energises you or feels like a daily grind...',
      },
      {
        id: 'forties-relationships',
        prompt: 'Who are the essential party members in your life right now?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Essential party',
        placeholder: 'Partner, kids, close friends, family — the people you would actually call at 2am...',
      },
      {
        id: 'forties-health',
        prompt: 'How is the character model holding up? (Health and body)',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Character condition',
        placeholder: 'Knees clicking, greying hair, fitter than ever — the physical reality of your forties...',
      },
      {
        id: 'forties-surprise',
        prompt: 'What has surprised you most about reaching this level?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Level surprise',
        placeholder: 'Something nobody warned you about, or something that turned out completely different than expected...',
      },
      {
        id: 'forties-unfinished',
        prompt: 'Any incomplete quests nagging at you from earlier chapters?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Incomplete quests',
        placeholder: 'A dream deferred, a conversation never had, a place never visited — the unchecked boxes...',
      },
      {
        id: 'forties-wisdom',
        prompt: 'What buff would you cast on your Level 20 self? (Advice to younger you)',
        type: 'textarea',
        required: false,
        xp: 30,
        timelineLabel: 'Wisdom buff',
        placeholder: 'The one thing you know now that would have saved you a lot of grinding back then...',
      },
    ],
  },
  {
    id: 'fifties-plus',
    number: 9,
    title: 'The Long Game',
    subtitle: '50+, Wisdom Years',
    description: 'The Long Game — experience points are high, and you have seen enough to know what matters.',
    questions: [
      {
        id: 'fifties-legacy',
        prompt: 'What legacy quest are you working on? (What do you want to leave behind?)',
        type: 'textarea',
        required: true,
        xp: 40,
        timelineLabel: 'Legacy quest',
        placeholder: 'A business, a family tradition, a body of work, a way of being — the mark you want to leave...',
      },
      {
        id: 'fifties-mastery',
        prompt: 'What skill have you truly mastered after all these levels?',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Mastered skill',
        placeholder: 'Something you can do with ease now that once seemed impossible — your maxed-out skill...',
      },
      {
        id: 'fifties-perspective',
        prompt: 'How has the game map changed from up here? (Perspective on life)',
        type: 'textarea',
        required: true,
        xp: 35,
        timelineLabel: 'Map perspective',
        placeholder: 'What looks bigger, what looks smaller — the things that seemed urgent that turned out not to matter...',
      },
      {
        id: 'fifties-gratitude',
        prompt: 'What are the top items in your gratitude inventory?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Gratitude inventory',
        placeholder: 'People, experiences, lucky breaks — the things you are genuinely thankful made it into your story...',
      },
      {
        id: 'fifties-still-learning',
        prompt: 'What new skill trees are you still exploring?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'New skill trees',
        placeholder: 'A new hobby, a new field, something you started learning just because you wanted to...',
      },
      {
        id: 'fifties-loss-wisdom',
        prompt: 'What has loss taught you about the game?',
        type: 'textarea',
        required: false,
        xp: 35,
        timelineLabel: 'Loss wisdom',
        placeholder: 'The heavy knowledge that only comes from losing something or someone — what it taught you...',
      },
    ],
  },
  {
    id: 'present-day',
    number: 10,
    title: 'Current Save',
    subtitle: 'Where You Are Right Now',
    description: 'Your current save file — snapshot of the hero at this exact moment in the timeline.',
    questions: [
      {
        id: 'present-location',
        prompt: 'Where is your character currently stationed? (City, suburb)',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'Current location',
        placeholder: 'The suburb, the city — the hum of traffic or the quiet of your street...',
      },
      {
        id: 'present-occupation',
        prompt: 'What is your current active quest? (Job, role, daily focus)',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'Active quest',
        placeholder: 'What you do day to day — the routine, the purpose, the Monday morning feeling...',
      },
      {
        id: 'present-mood',
        prompt: 'Check your status screen — what is your current morale level?',
        type: 'select',
        required: true,
        xp: 15,
        timelineLabel: 'Morale level',
        options: [
          'Legendary — Best shape of my life',
          'Strong — Good, with minor debuffs',
          'Steady — Grinding along, stable',
          'Weathered — Dealing with some damage',
          'Critical — Need a healing potion',
        ],
      },
      {
        id: 'present-proud',
        prompt: 'What are you most proud of in your current save file?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Current pride',
        placeholder: 'A relationship, a skill, a possession, a habit — the thing that makes you think "yeah, that is good"...',
      },
      {
        id: 'present-struggle',
        prompt: 'What is the current boss fight you are facing?',
        type: 'textarea',
        required: false,
        xp: 30,
        timelineLabel: 'Current boss fight',
        placeholder: 'A challenge, a decision, an ongoing battle — the thing keeping you up at night...',
      },
      {
        id: 'present-goal',
        prompt: 'What quest marker is on your horizon? (Next big goal)',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Next quest marker',
        placeholder: 'Something you are working towards — the next milestone, the next chapter you want to write...',
      },
      {
        id: 'present-message',
        prompt: 'If you could pin a message to your save file for future you, what would it say?',
        type: 'textarea',
        required: false,
        xp: 30,
        timelineLabel: 'Pinned message',
        placeholder: 'A reminder, a warning, an encouragement — words for the hero who will load this save later...',
      },
    ],
  },
];

const allQuestions = CHAPTERS.flatMap((chapter) => chapter.questions);

export const TOTAL_QUESTIONS: number = allQuestions.length;

export const TOTAL_XP: number = allQuestions.reduce(
  (sum, question) => sum + question.xp,
  0,
);
