import type { ChapterDefinition } from '@/types/chronicle.types';

export const CHAPTERS: ChapterDefinition[] = [
  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 1: BIRTH
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'birth',
    number: 1,
    title: 'The Beginning',
    subtitle: 'Chapter I',
    description: 'Every legend has an origin story. Let\u2019s start yours.',
    questions: [
      {
        id: 'full-name',
        prompt: 'Hero, what name was bestowed upon you at the start of your quest?',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'Name given',
        placeholder: 'Your full name as it appears on the character sheet',
      },
      {
        id: 'date-of-birth',
        prompt: 'On what day did you first enter this world? The date your save file was created.',
        type: 'date',
        required: true,
        xp: 10,
        timelineLabel: 'Born',
      },
      {
        id: 'birthplace',
        prompt: 'Where did you spawn into existence? Which hospital, town, or kitchen floor?',
        type: 'text',
        required: true,
        xp: 15,
        timelineLabel: 'Birthplace',
        placeholder: 'The hospital or place where you were born',
      },
      {
        id: 'birth-story',
        prompt: 'Every arrival has a tale. What do you know about the day you showed up? Were you early, late, dramatic, or suspiciously quiet?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Birth story',
        placeholder: 'What your parents told you about the day — the weather, the rush, the relief...',
      },
      {
        id: 'parents',
        prompt: 'Who were the NPCs responsible for your character creation? Tell us about your parents or guardians.',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'Parents',
        placeholder: 'Their names, what they did, what they were like...',
      },
      {
        id: 'siblings',
        prompt: 'Did you have any party members from the start? Brothers, sisters, or companions who shared your early base camp?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Siblings',
        placeholder: 'Names, birth order, the dynamic between you...',
      },
      {
        id: 'name-meaning',
        prompt: 'Do you know why your name was chosen? Was there a story, a family tradition, or a last-minute change?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Name origin',
        placeholder: 'The reason behind your name — family tradition, a favourite book, pure whim...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 2: EARLY YEARS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'early-years',
    number: 2,
    title: 'Tutorial Zone',
    subtitle: 'Chapter II',
    description: 'Ages 0\u20135. The earliest memories, first steps, and tutorial-level skills.',
    questions: [
      {
        id: 'first-home',
        prompt: 'Where was your first base of operations? Describe the house or flat where your earliest memories formed.',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'First home',
        placeholder: 'The feel of the carpet, the smell of the kitchen, the sound of the street outside...',
      },
      {
        id: 'earliest-memory',
        prompt: 'What is the earliest memory in your save file? The very first thing you can recall — even if it\u2019s just a fragment.',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Earliest memory',
        placeholder: 'A texture, a sound, a feeling — even the smallest fragment counts...',
      },
      {
        id: 'comfort-item',
        prompt: 'Every young adventurer has a starter item. What was yours? A blanket, a toy, something you wouldn\u2019t let go of?',
        type: 'text',
        required: false,
        xp: 15,
        timelineLabel: 'Comfort item',
        placeholder: 'That one thing you carried everywhere...',
      },
      {
        id: 'first-pet',
        prompt: 'Did your party include a companion creature? A dog, cat, goldfish, or imaginary dragon?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'First pet',
        placeholder: 'Name, species, temperament, the warmth of their fur or the cold of the tank...',
      },
      {
        id: 'family-tradition',
        prompt: 'What was a regular ritual in your household? Sunday roasts, beach trips, Friday night takeaway?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Family tradition',
        placeholder: 'The routine that felt like home — the smells, the sounds, who was there...',
      },
      {
        id: 'favourite-food-kid',
        prompt: 'What was your go-to fuel as a tiny adventurer? The meal you would have eaten every day if allowed.',
        type: 'text',
        required: false,
        xp: 10,
        timelineLabel: 'Favourite food',
        placeholder: 'The one thing you always wanted for dinner...',
      },
      {
        id: 'kindergarten',
        prompt: 'Do you remember kindy or daycare? What was the vibe — chaotic, cosy, terrifying, or a blur?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Kindergarten',
        placeholder: 'The smell of play-dough, the sand pit, nap time on the mat...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 3: PRIMARY SCHOOL
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'primary-school',
    number: 3,
    title: 'The Academy',
    subtitle: 'Chapter III',
    description: 'Your first real training ground. Friends made, skills learned, playground politics navigated.',
    questions: [
      {
        id: 'school-name',
        prompt: 'What was the name of your training academy? The school where you first learned the ways of the world.',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'Primary school',
        placeholder: 'The name of your primary school',
      },
      {
        id: 'best-friend',
        prompt: 'Who was your first true ally? The friend you sat next to, played with at lunch, or walked home with.',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'Best friend',
        placeholder: 'Their name, how you met, what you did together...',
      },
      {
        id: 'favourite-subject',
        prompt: 'Which skill tree did you naturally gravitate towards? What subject made the hours disappear?',
        type: 'text',
        required: false,
        xp: 10,
        timelineLabel: 'Favourite subject',
        placeholder: 'The class you actually looked forward to...',
      },
      {
        id: 'playground-memory',
        prompt: 'The playground was your open-world sandbox. What\u2019s a memory that stuck? A game, an incident, a moment.',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Playground memory',
        placeholder: 'The heat of the bitumen, the bell ringing, the game everyone played...',
      },
      {
        id: 'favourite-teacher',
        prompt: 'Was there a mentor NPC who made a real difference? A teacher who saw something in you.',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Favourite teacher',
        placeholder: 'Their name, what they taught, why they mattered...',
      },
      {
        id: 'school-sport',
        prompt: 'Did you pick up any physical skills during this chapter? Sport, swimming, athletics?',
        type: 'text',
        required: false,
        xp: 10,
        timelineLabel: 'Sport',
        placeholder: 'The sport or activity you were into...',
      },
      {
        id: 'family-holiday',
        prompt: 'What was a standout holiday or trip from this era? The one your family still talks about.',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Family holiday',
        placeholder: 'Where you went, the car trip there, the smell of sunscreen and salt water...',
      },
      {
        id: 'childhood-fear',
        prompt: 'Every hero has an early-game weakness. What scared you as a kid? Storms, the dark, a specific sound?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Childhood fear',
        placeholder: 'The thing that made you pull the covers over your head...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 4: TEENS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'teens',
    number: 4,
    title: 'Coming of Age',
    subtitle: 'Chapter IV',
    description: 'The difficulty spike. Identity forming, friendships deepening, the world getting bigger.',
    questions: [
      {
        id: 'high-school',
        prompt: 'Welcome to the advanced academy. What high school did you attend?',
        type: 'text',
        required: true,
        xp: 10,
        timelineLabel: 'High school',
        placeholder: 'The name of your high school',
      },
      {
        id: 'teen-identity',
        prompt: 'What kind of character build were you? The sporty one, the quiet one, the class clown, the invisible one?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Teen identity',
        placeholder: 'How you saw yourself — or how others saw you...',
      },
      {
        id: 'first-job',
        prompt: 'When did you first trade time for gold? Your first job — paid or otherwise.',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'First job',
        placeholder: 'The place, the pay, the sticky floors or early mornings...',
      },
      {
        id: 'teen-music',
        prompt: 'What was the soundtrack to this chapter? The band, genre, or song that defined your teens.',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Teen music',
        placeholder: 'The music that still takes you straight back...',
      },
      {
        id: 'hardest-lesson',
        prompt: 'What was the hardest lesson this chapter taught you? Not school work — a life lesson.',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Hard lesson',
        placeholder: 'The moment that changed how you understood something important...',
      },
      {
        id: 'teen-hangout',
        prompt: 'Where was your crew\u2019s base camp? The place you\u2019d gather — a park, a mate\u2019s house, a shopping centre food court?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Hangout spot',
        placeholder: 'The place and the feeling of being there with your people...',
      },
      {
        id: 'year-12',
        prompt: 'How did the academy finale go? Did you finish Year 12, leave early, or take a different path?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Year 12',
        placeholder: 'How school ended — the relief, the uncertainty, the next step...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 5: YOUNG ADULT
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'young-adult',
    number: 5,
    title: 'Open World',
    subtitle: 'Chapter V',
    description: 'Ages 18\u201324. The map opens up. First real independence, choices with consequences.',
    questions: [
      {
        id: 'first-independence',
        prompt: 'When did you first leave the starting village? Moving out, going to uni, starting full-time work?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Independence',
        placeholder: 'The moment you were properly on your own...',
      },
      {
        id: 'career-start',
        prompt: 'What was your first real career quest? Not just a job — the thing you thought might become your path.',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Career start',
        placeholder: 'The role, the company, the first day nerves...',
      },
      {
        id: 'first-home-own',
        prompt: 'Where did you set up your own base camp for the first time? A share house, a unit, a room you rented?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'First own place',
        placeholder: 'The address, the mismatched furniture, the freedom...',
      },
      {
        id: 'young-adventure',
        prompt: 'Did you go on any major side quests? Travel, a big move, a spontaneous decision that changed things?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Adventure',
        placeholder: 'The trip, the move, the leap of faith...',
      },
      {
        id: 'important-relationship',
        prompt: 'Who was an important person in this chapter? A partner, mentor, friend, or rival who shaped your path.',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Key relationship',
        placeholder: 'Who they were, how you met, what they meant to your story...',
      },
      {
        id: 'young-mistake',
        prompt: 'What\u2019s a decision from this era you\u2019d handle differently with a second playthrough?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Lesson learned',
        placeholder: 'Not regret — just the wisdom of hindsight...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 6: LATE TWENTIES
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'late-twenties',
    number: 6,
    title: 'The Grind',
    subtitle: 'Chapter VI',
    description: 'Ages 25\u201329. Levelling up gets harder. Career pressure, financial reality, adult responsibilities.',
    questions: [
      {
        id: 'career-direction',
        prompt: 'By now your skill tree was taking shape. What were you doing for work, and was it where you expected to be?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Career path',
        placeholder: 'The role, the industry, whether it felt right...',
      },
      {
        id: 'financial-wake-up',
        prompt: 'When did gold management become real? The moment you realised money wasn\u2019t infinite.',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Financial reality',
        placeholder: 'The bill, the rent hike, the empty account, the first real budget...',
      },
      {
        id: 'living-situation',
        prompt: 'Where were you based? Did you buy, rent, share, or bounce between places?',
        type: 'textarea',
        required: true,
        xp: 20,
        timelineLabel: 'Living situation',
        placeholder: 'The place, the flatmates, the neighbourhood...',
      },
      {
        id: 'twenties-achievement',
        prompt: 'What\u2019s something you accomplished in your twenties that you\u2019re genuinely proud of?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Achievement',
        placeholder: 'A milestone, a goal reached, a thing you built...',
      },
      {
        id: 'twenties-struggle',
        prompt: 'What was the hardest boss fight of this chapter? A challenge that tested your endurance.',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Major challenge',
        placeholder: 'The situation, how it felt, how you got through it...',
      },
      {
        id: 'twenties-friendship',
        prompt: 'Which friendships from this era are still in your active party today?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Lasting friendships',
        placeholder: 'The mates who stuck around...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 7: THIRTIES
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'thirties',
    number: 7,
    title: 'Peak Power',
    subtitle: 'Chapter VII',
    description: 'Ages 30\u201339. The big decisions. Career peaks, property, family, and knowing yourself better.',
    questions: [
      {
        id: 'thirties-career',
        prompt: 'How did your career evolve in this chapter? Promotions, pivots, or building something of your own?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Career evolution',
        placeholder: 'The moves you made, the risks you took...',
      },
      {
        id: 'property-journey',
        prompt: 'Did you enter the property market? Buy, invest, or decide it wasn\u2019t for you?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Property',
        placeholder: 'The search, the auction, the settlement day nerves...',
      },
      {
        id: 'family-changes',
        prompt: 'What changed in your family landscape? New arrivals, losses, relationships shifting?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Family changes',
        placeholder: 'Births, deaths, marriages, separations — the big shifts...',
      },
      {
        id: 'thirties-identity',
        prompt: 'By your thirties, did you feel like you knew who you were? Or were you still figuring it out?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Self-knowledge',
        placeholder: 'What you\u2019d learned about yourself that younger you didn\u2019t know...',
      },
      {
        id: 'thirties-health',
        prompt: 'How was your health stat in this chapter? Any wake-up calls, new habits, or changes?',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Health',
        placeholder: 'The gym phase, the injury, the doctor visit, the lifestyle change...',
      },
      {
        id: 'proudest-moment-30s',
        prompt: 'What\u2019s the moment from this decade you\u2019d replay if you could?',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Proudest moment',
        placeholder: 'The achievement, the feeling, where you were standing...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 8: FORTIES
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'forties',
    number: 8,
    title: 'The Plateau',
    subtitle: 'Chapter VIII',
    description: 'Ages 40\u201349. Stability, reflection, and the wisdom of experience. Or a complete reinvention.',
    questions: [
      {
        id: 'forties-life-state',
        prompt: 'Paint the picture of your life at 40. Where were you living, who were you with, what were you doing?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Life at 40',
        placeholder: 'The daily routine, the morning coffee, the drive to work...',
      },
      {
        id: 'forties-priorities',
        prompt: 'What mattered most in this chapter? Did your priorities shift from the previous decade?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Priorities',
        placeholder: 'What you stopped caring about, and what became essential...',
      },
      {
        id: 'forties-surprise',
        prompt: 'What would 20-year-old you be most surprised about regarding how things turned out?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Surprise',
        placeholder: 'The thing you never expected about your own life...',
      },
      {
        id: 'forties-loss',
        prompt: 'Did you lose anyone important during this chapter? A parent, friend, or someone who left a gap.',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Loss',
        placeholder: 'Who they were, what they meant, the shape of their absence...',
      },
      {
        id: 'forties-hobby',
        prompt: 'Did you pick up any new skills or hobbies in this chapter? Things you do purely because you enjoy them.',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'New hobby',
        placeholder: 'The thing you started doing just for yourself...',
      },
      {
        id: 'forties-wisdom',
        prompt: 'What\u2019s a piece of wisdom from this chapter you\u2019d pass on to someone entering their forties?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Wisdom',
        placeholder: 'The advice you\u2019d give — honest, practical, from experience...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 9: FIFTIES+
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'fifties-plus',
    number: 9,
    title: 'The Long Game',
    subtitle: 'Chapter IX',
    description: 'Age 50 and beyond. The long view. Legacy, perspective, and the things that endure.',
    questions: [
      {
        id: 'fifties-perspective',
        prompt: 'Looking back at the full quest so far, what pattern do you see in your story that wasn\u2019t obvious at the time?',
        type: 'textarea',
        required: true,
        xp: 30,
        timelineLabel: 'Life pattern',
        placeholder: 'The thread that runs through your story...',
      },
      {
        id: 'fifties-relationships',
        prompt: 'Which relationships have been the most enduring? The ones that weathered every chapter.',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Lasting bonds',
        placeholder: 'The people who\u2019ve been there through it all...',
      },
      {
        id: 'fifties-legacy',
        prompt: 'What would you want to be remembered for? Not your job title — the thing that matters.',
        type: 'textarea',
        required: false,
        xp: 25,
        timelineLabel: 'Legacy',
        placeholder: 'The mark you\u2019d want to leave...',
      },
      {
        id: 'fifties-regret',
        prompt: 'Is there an unexplored side quest you wish you\u2019d taken? Something you still think about.',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Unexplored quest',
        placeholder: 'The path not taken...',
      },
      {
        id: 'fifties-gratitude',
        prompt: 'What are you most grateful for when you look at the full inventory of your life?',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Gratitude',
        placeholder: 'The things, people, or experiences you wouldn\u2019t trade...',
      },
      {
        id: 'fifties-surprise-joy',
        prompt: 'What\u2019s brought you unexpected joy in recent years? The thing you didn\u2019t see coming.',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Unexpected joy',
        placeholder: 'The surprise that made life richer...',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 10: PRESENT DAY
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'present-day',
    number: 10,
    title: 'Current Save',
    subtitle: 'Chapter X',
    description: 'Right now. Where you are today, what drives you, and what comes next.',
    questions: [
      {
        id: 'current-state',
        prompt: 'Describe your current save file. Where are you living, what are you doing, how does a typical day feel?',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Current state',
        placeholder: 'The morning alarm, the commute, the evening routine...',
      },
      {
        id: 'current-drives',
        prompt: 'What\u2019s driving you right now? The goals, motivations, or restless feelings pushing you forward.',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Motivations',
        placeholder: 'What gets you out of bed, what keeps you up at night...',
      },
      {
        id: 'current-challenge',
        prompt: 'What\u2019s the active boss fight in your life right now? The challenge you\u2019re currently facing.',
        type: 'textarea',
        required: false,
        xp: 20,
        timelineLabel: 'Current challenge',
        placeholder: 'The thing you\u2019re working through...',
      },
      {
        id: 'current-joy',
        prompt: 'What\u2019s bringing you the most satisfaction lately? The thing that feels genuinely good.',
        type: 'textarea',
        required: false,
        xp: 15,
        timelineLabel: 'Current joy',
        placeholder: 'The activity, person, or routine that recharges you...',
      },
      {
        id: 'next-quest',
        prompt: 'If you could start one new quest tomorrow, what would it be? No limitations.',
        type: 'textarea',
        required: true,
        xp: 25,
        timelineLabel: 'Next quest',
        placeholder: 'The thing you\u2019d do if fear and logistics weren\u2019t factors...',
      },
      {
        id: 'letter-to-past',
        prompt: 'If you could send a one-paragraph message back to Chapter 1 you, what would it say?',
        type: 'textarea',
        required: false,
        xp: 30,
        timelineLabel: 'Letter to past self',
        placeholder: 'The honest words you\u2019d want younger you to hear...',
      },
    ],
  },
];

export const TOTAL_QUESTIONS: number = CHAPTERS.reduce(
  (sum, ch) => sum + ch.questions.length,
  0,
);

export const TOTAL_XP: number = CHAPTERS.reduce(
  (sum, ch) =>
    sum + ch.questions.reduce((qSum, q) => qSum + q.xp, 0),
  0,
);
