import { useState, useCallback, useMemo } from 'react';
import { useData } from '@/services/DataContext';
import { saveToFile } from '@/services/local-data.service';
import { CHAPTERS } from '@/features/chronicle/chapters';
import type { ChronicleAnswer } from '@/types/chronicle.types';

function ExportSkeleton() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      {[1, 2, 3].map((n) => (
        <div
          key={`export-skel-${n}`}
          className="rounded-xl p-5 bg-[var(--color-surface-card)] border border-[var(--color-border)]"
        >
          <div className="skeleton h-5 w-40 mb-3" />
          <div className="skeleton h-3 w-full mb-2" />
          <div className="skeleton h-3 w-3/4 mb-4" />
          <div className="skeleton h-10 w-full rounded-lg" />
        </div>
      ))}
    </div>
  );
}

function formatDateAU(isoDate: string): string {
  if (!isoDate) return '';
  const d = new Date(isoDate);
  if (isNaN(d.getTime())) return isoDate;
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}/${month}/${year}`;
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildMemoirHTML(
  answers: Record<string, ChronicleAnswer>,
  displayName: string,
): string {
  const dateStamp = formatDateAU(new Date().toISOString());

  const chaptersHTML = CHAPTERS.map((chapter) => {
    const chapterAnswers = chapter.questions
      .filter((q) => answers[q.id] != null)
      .map((q) => {
        const answer = answers[q.id]!;
        return `
        <div style="margin-bottom: 24px;">
          <p style="color: #b0a090; font-size: 14px; margin: 0 0 6px 0; font-style: italic;">
            ${escapeHTML(q.prompt)}
          </p>
          <p style="color: #e8dcc8; font-size: 16px; margin: 0; line-height: 1.7; white-space: pre-wrap;">
            ${escapeHTML(answer.value)}
          </p>
          ${
            answer.followUpQuestion && answer.followUpAnswer
              ? `
          <div style="margin-top: 12px; padding-left: 16px; border-left: 2px solid #d4a44a33;">
            <p style="color: #b0a090; font-size: 13px; margin: 0 0 4px 0; font-style: italic;">
              ${escapeHTML(answer.followUpQuestion)}
            </p>
            <p style="color: #e8dcc8; font-size: 15px; margin: 0; line-height: 1.7; white-space: pre-wrap;">
              ${escapeHTML(answer.followUpAnswer)}
            </p>
          </div>`
              : ''
          }
        </div>`;
      })
      .join('');

    if (!chapterAnswers) return '';

    return `
      <div style="margin-bottom: 48px;">
        <h2 style="color: #d4a44a; font-family: Georgia, serif; font-size: 24px; margin: 0 0 4px 0;">
          Chapter ${chapter.number}: ${escapeHTML(chapter.title)}
        </h2>
        <p style="color: #8a7a6a; font-size: 14px; margin: 0 0 24px 0;">
          ${escapeHTML(chapter.subtitle)}
        </p>
        ${chapterAnswers}
      </div>`;
  })
    .filter(Boolean)
    .join('');

  const title = displayName ? `${escapeHTML(displayName)}'s Life Chronicle` : 'Life Chronicle';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #1a1410; color: #e8dcc8; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <div style="max-width: 720px; margin: 0 auto; padding: 48px 24px;">
    <header style="text-align: center; margin-bottom: 64px; border-bottom: 1px solid #d4a44a33; padding-bottom: 32px;">
      <h1 style="color: #d4a44a; font-family: Georgia, serif; font-size: 36px; margin: 0 0 8px 0;">
        ${title}
      </h1>
      <p style="color: #8a7a6a; font-size: 14px; margin: 0;">
        Exported on ${dateStamp} &mdash; Generated by Life OS
      </p>
    </header>
    <main>
      ${chaptersHTML || '<p style="color: #8a7a6a; text-align: center;">No chronicle answers recorded yet.</p>'}
    </main>
    <footer style="text-align: center; margin-top: 64px; padding-top: 32px; border-top: 1px solid #d4a44a33;">
      <p style="color: #5a4a3a; font-size: 12px; margin: 0;">
        Life OS &mdash; Your story, stored locally, owned by you.
      </p>
    </footer>
  </div>
</body>
</html>`;
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

interface ExportCardProps {
  title: string;
  description: string;
  buttonLabel: string;
  onClick: () => void;
}

function ExportCard({ title, description, buttonLabel, onClick }: ExportCardProps) {
  return (
    <div className="rounded-xl p-5 bg-[var(--color-surface-card)] border border-[var(--color-border)] flex flex-col">
      <h3 className="text-lg font-display font-semibold text-text-primary mb-2">
        {title}
      </h3>
      <p className="text-sm text-text-secondary font-body leading-relaxed mb-4 flex-1">
        {description}
      </p>
      <button
        type="button"
        onClick={onClick}
        className="w-full px-4 py-2.5 rounded-lg bg-[var(--color-accent)] text-white text-sm font-body hover:bg-[var(--color-accent-hover)] transition-colors"
      >
        {buttonLabel}
      </button>
    </div>
  );
}

export function ExportHub() {
  const { data } = useData();
  const [isLoading] = useState(false);

  const dateStamp = useMemo(() => new Date().toISOString().split('T')[0], []);

  const nameSlug = useMemo(() => {
    const name = data.profile.displayName;
    return name ? name.toLowerCase().replace(/\s+/g, '-') : 'life-os';
  }, [data.profile.displayName]);

  const handleExportFull = useCallback(() => {
    saveToFile(data);
  }, [data]);

  const handleExportHTML = useCallback(() => {
    const html = buildMemoirHTML(data.chronicle.answers, data.profile.displayName);
    const blob = new Blob([html], { type: 'text/html' });
    downloadBlob(blob, `${nameSlug}-memoir-${dateStamp}.html`);
  }, [data.chronicle.answers, data.profile.displayName, nameSlug, dateStamp]);

  const handleExportChronicle = useCallback(() => {
    const chronicleExport = CHAPTERS.map((chapter) => {
      const chapterAnswers = chapter.questions
        .filter((q) => data.chronicle.answers[q.id] != null)
        .map((q) => {
          const a = data.chronicle.answers[q.id]!;
          return {
            question: q.prompt,
            answer: a.value,
            answeredAt: a.answeredAt,
            ...(a.followUpQuestion
              ? {
                  followUpQuestion: a.followUpQuestion,
                  followUpAnswer: a.followUpAnswer,
                }
              : {}),
          };
        });

      if (chapterAnswers.length === 0) return null;

      return {
        chapter: chapter.number,
        title: chapter.title,
        subtitle: chapter.subtitle,
        answers: chapterAnswers,
      };
    }).filter(Boolean);

    const json = JSON.stringify(chronicleExport, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    downloadBlob(blob, `${nameSlug}-chronicle-${dateStamp}.json`);
  }, [data.chronicle.answers, nameSlug, dateStamp]);

  if (isLoading) {
    return (
      <div className="p-6">
        <h2 className="text-2xl font-display font-bold text-text-primary mb-6">
          Export Centre
        </h2>
        <ExportSkeleton />
      </div>
    );
  }

  return (
    <div className="p-6 max-w-3xl">
      <h2 className="text-2xl font-display font-bold text-text-primary mb-2">
        Export Centre
      </h2>
      <p className="text-sm text-text-secondary font-body mb-6">
        Your data, your formats. Everything stays on your machine.
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <ExportCard
          title="Download .lifeos.json"
          description="Export your complete Life OS dataset — all chronicle answers, journal entries, thoughts, connections, letters, and financial data in one file."
          buttonLabel="Download Full Backup"
          onClick={handleExportFull}
        />

        <ExportCard
          title="Export as HTML"
          description="Generate a self-contained HTML memoir with all your chronicle answers formatted as readable chapters. Opens in any browser, no internet needed."
          buttonLabel="Export HTML Memoir"
          onClick={handleExportHTML}
        />

        <ExportCard
          title="Export Chronicle Only"
          description="Just your chronicle answers as clean JSON — questions, responses, and follow-ups grouped by chapter. Lightweight and portable."
          buttonLabel="Export Chronicle JSON"
          onClick={handleExportChronicle}
        />
      </div>
    </div>
  );
}
